### ISSUE TITLE
Mixer issues

### ISSUE THREAD

**Issue by liorella-qm** [qua-platform/py-qua-tools#88] opened 2022-03-21 13:20 UTC
the mixer type and the mixer definition in the schema are not consistent. The mixer is a list of dictionaries with keys `intermediate_frequency`, `correction`, `lo_frequency`, see [here](https://qm-docs.qualang.io/qm_config.html#null%2Fpaths%2F~1%2Fget)

![image](https://user-images.githubusercontent.com/73523466/159269266-a1e8230f-6dc5-427b-a236-7189045321da.png)

**Comment by SatyaBade12** [comment] 2022-04-15 14:13
mixers field in the final configuration generated by the builder seems to be correct (we also have a unit test). Could you provide a minimal reproducible example that shows the inconsistency?

**Comment by SatyaBade12** [comment] 2022-05-11 12:21
this is fixed now, we can add correction matrix for every pair of IF and LO

**Closed by SatyaBade12** 2022-05-11 12:21 UTC
Labels: bug
